#!/bin/sh

# checks if the image exists, if not, it is created
$(dirname $0)/../docker/docker-create.sh pandoc

# run docker container
docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data -v ~/.pandoc:/pandoc dotfiles/pandoc --data-dir=/pandoc "$@"

# redirects the exit status
exit $?
